object prtm {
	import rosalind.WeightTable
	
	val data = "VEMMSCNENEEVPWHYNKKYTARSINKKFHTGRRGWDVLNWTVCKNTRSVLGIPEKMVQWSAVLTNDQTPMMGNNNLPVELYYMQGASIERCAWWGAHHCHYSQIMKYIEGADRPCTQKAGASVSTSNWYGASGICRNPSKMTCVQESHVFFCFWFCRGKEDFDTFGLTPYRSTPCNHWTIQCGMSSDCYRNGMKQIGAWRMTRDNETDNTKYYMWRFWRREDTGDMCEGYLQEQDPWFMRGMYACIYYCFRQRGCQAYPYIIGAQQKSKEAYIDKKIRYRLLHYWCGHMFPIEFCKLTAMAAAFLTVQHAICCRSFDRLKFTPAYCNGSTEQTCIWFMHMKEGIKYMPNARNFEDPQKFTVPRQAYCPLMPESNNEQGKQLVAVSLKFRADCGLWAHYTICVNALELHNIQHMALYQMWWCHCIIACNPDKNWRNVKTVWGFYHNEELNWDTEDAFAPAAHYTIEYMCFWLCLTDPDCIGTIVIAIFFNLRMQRNHFFLVSCAWVGFPILATLANICLPINHNMWSVPPSMQIEHGGWPPFEYTPLWDFQLRASPGFMQTDGPNDPMNPTKAWRTGWPGLLGMGGGKHFDSCWTNIEWRQRYVVDPNEEVIPRKERSYEKQFFCCLQDCCPTKFKTWQIPWWNALLCAYKCIPKKWKGMGYQKPVKKDLRKAMDHAEDACPIYGFEIFMGISSPWGPYMPDDDFGDPEEDSESEYHVAKYLNLRTKAEMRHTQDCKSCIGCAHEKYFRNTHDVDKMTHLEIANWPYTMAFCHMHMCFIWHGWRQHVVTAQMQPIDVDAHHYIISGDIPFWFRNVRIHLASFYEKEAFHNKVQHFMISVEFANQTFRLFLQNQSCTSLMPCHMGNRYHHWMMWCHYTGINCCARGWDQDLHFAQDWWNYYLCWGVENKMKCSSVSVHEFHILCNLMCKFHNTDHMLAMGPWVTTANIWHMPYTQKHWVICKDP"
                                                  //> data  : String = VEMMSCNENEEVPWHYNKKYTARSINKKFHTGRRGWDVLNWTVCKNTRSVLGIPEKMV
                                                  //| QWSAVLTNDQTPMMGNNNLPVELYYMQGASIERCAWWGAHHCHYSQIMKYIEGADRPCTQKAGASVSTSNWYGAS
                                                  //| GICRNPSKMTCVQESHVFFCFWFCRGKEDFDTFGLTPYRSTPCNHWTIQCGMSSDCYRNGMKQIGAWRMTRDNET
                                                  //| DNTKYYMWRFWRREDTGDMCEGYLQEQDPWFMRGMYACIYYCFRQRGCQAYPYIIGAQQKSKEAYIDKKIRYRLL
                                                  //| HYWCGHMFPIEFCKLTAMAAAFLTVQHAICCRSFDRLKFTPAYCNGSTEQTCIWFMHMKEGIKYMPNARNFEDPQ
                                                  //| KFTVPRQAYCPLMPESNNEQGKQLVAVSLKFRADCGLWAHYTICVNALELHNIQHMALYQMWWCHCIIACNPDKN
                                                  //| WRNVKTVWGFYHNEELNWDTEDAFAPAAHYTIEYMCFWLCLTDPDCIGTIVIAIFFNLRMQRNHFFLVSCAWVGF
                                                  //| PILATLANICLPINHNMWSVPPSMQIEHGGWPPFEYTPLWDFQLRASPGFMQTDGPNDPMNPTKAWRTGWPGLLG
                                                  //| MGGGKHFDSCWTNIEWRQRYVVDPNEEVIPRKERSYEKQFFCCLQDCCPTKFKTWQIPWWNALLCAYKCIPKKWK
                                                  //| GMGYQKPVKKDLRKAMDHAEDACPIYGFEIFMGISSPWGPYMPDDDFGDPEEDSESEYHVAKYLNLRTKAEMRHT
                                                  //| QDCKSCIGCAHEKYFRNTHDVDKMTHLEIANWPYTMAFCHMHMCFIWHGWRQHVVTAQMQPIDVDAHHYIISGDI
                                                  //| PFWFRNVRIHLASFYEKEAFHNKVQHFMISVEFANQTFRLFLQNQSCTSLMPCHMGNRYHHWMMWCHYTGINCCA
                                                  //| RGWDQDLHFAQDWWNYYLCWGVE
                                                  //| Output exceeds cutoff limit.
	data.toStream.foldLeft(0d)((acc, letter) => {
		acc + WeightTable(letter)
	})                                        //> res0: Double = 113793.03960000053
}